server:
  port: 8090

spring:
  redis:
    # 单个 Redis 配置
    #    host: 192.168.190.134
    #    port: 6379
    #    password: 123456
    #    database: 0
    #    lettuce:
    #      pool:
    #        max-idle: 16
    #        max-active: 32
    #        min-idle: 8
    # Redis 集群配置
    cluster:
      nodes: 192.168.190.134:6379,192.168.190.134:6380,192.168.190.134:6381
      max-redirects: 3
