server:
  port: 8090

spring:
  application:
    name: studynotes-mybatis
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.190.134:3306/study_notes?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: W110514

mybatis:
  # 加载 Mapper 映射文件
  mapper-locations: classpath:mapper/*.xml
